###
POST https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "UPC1",
  "UpcProm": null,
  "ProductId": "9ff5c278-6436-496b-bf32-191e1bfb08df",
  "Price": 100.00,
  "Quantity": 10,
  "IsPromotional": false
}
###
POST https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "UPC2",
  "UpcProm": null,
  "ProductId": "84636828-030d-4506-a08e-b2aeb5ef869c",
  "Price": 200.00,
  "Quantity": 20,
  "IsPromotional": false
}
###
POST https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "UPC3",
  "UpcProm": null,
  "ProductId": "cd9bff9e-8c4b-4311-81b9-7e41d0cd52ca",
  "Price": 300.00,
  "Quantity": 30,
  "IsPromotional": false
}
###
GET https://localhost:5001/api/store-products/Test
Accept: application/json
###
GET https://localhost:5001/api/store-products
Accept: application/json

###
PUT https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "UPC99",
  "UpcProm": null,
  "ProductId": "cd9bff9e-8c4b-4311-81b9-7e41d0cd52ca",
  "Price": 300.00,
  "Quantity": 50,
  "IsPromotional": false
}
###
DELETE https://localhost:5001/api/store-products/UPC1
Content-Type: application/json

###
GET https://localhost:5001/api/store-products/not-promo/upcs
Accept: application/json