GET https://localhost:5001/api/products/{GUID}
Accept: application/json
###
GET https://localhost:5001/api/products
Accept: application/json
###
PUT https://localhost:5001/api/products/{GUID}
Content-Type: application/json

{
  "Name": "Updated product name",
  "CategoryId": 1,
  "Characteristics": "Updated Char 0"
}
###
DELETE https://localhost:5001/api/products/{GUID}
Accept: application/json
###
POST https://localhost:5001/api/products
Content-Type: application/json

{
  "Name": "Product name",
  "CategoryId": 1,
  "Characteristics": "Char 0"
}
###
GET https://localhost:5001/api/customer-card/{GUID}
Accept: application/json
###
GET https://localhost:5001/api/customer-card
Accept: application/json
###
PUT https://localhost:5001/api/customer-card/{GUID}
Content-Type: application/json

{
  "Surname": "surname",
  "Name": "name",
  "Patronymic": null,
  "Phone": "+380000000000",
  "City": null,
  "Street": null,
  "Index": null,
  "Percentage": 0
}
###
DELETE https://localhost:5001/api/customer-card/{GUID}
Accept: application/json
###
POST https://localhost:5001/api/customer-card
Content-Type: application/json

{
  "Surname": "surname",
  "Name": "name",
  "Patronymic": null,
  "Phone": "+380000000000",
  "City": null,
  "Street": null,
  "Index": null,
  "Percentage": 0
}###
GET https://localhost:5001/api/employees/{GUID}
Accept: application/json
###
GET https://localhost:5001/api/employees
Accept: application/json
###
PUT https://localhost:5001/api/employees/{GUID}
Content-Type: application/json

{
  "Surname": "Surname",
  "Name": "Name",
  "Patronymic": null,
  "Role": "Role",
  "Salary": 0,
  "DateOfBirth": "",
  "DateOfStart": "",
  "PhoneNumber": "+380000000000",
  "City": "City",
  "Street": "Street",
  "ZipCode": "ZipCode"
}
###
DELETE https://localhost:5001/api/employees/{GUID}
Accept: application/json
###
POST https://localhost:5001/api/employees
Content-Type: application/json

{
  "Surname": "Surname",
  "Name": "Name",
  "Patronymic": null,
  "Role": "Role",
  "Salary": 0,
  "DateOfBirth": "",
  "DateOfStart": "",
  "PhoneNumber": "+380000000000",
  "City": "City",
  "Street": "Street",
  "ZipCode": "ZipCode"
}