GET https://localhost:5001/api/products/{GUID}
Accept: application/json
###
GET https://localhost:5001/api/products
Accept: application/json
###
PUT https://localhost:5001/api/products/{GUID}
Content-Type: application/json

{
  "Name": "Updated product name",
  "CategoryId": 1,
  "Characteristics": "Updated Char 0"
}
###
DELETE https://localhost:5001/api/products/{GUID}
Accept: application/json
###
POST https://localhost:5001/api/products
Content-Type: application/json

{
  "Name": "Product name",
  "CategoryId": 1,
  "Characteristics": "Char 0"
}


###
POST https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "123456789012",
  "UpcProm": null,
  "ProductId": "0ce7436c-aa16-4eea-8b23-01fdf1744f2e",
  "Price": 9.99,
  "Quantity": 100,
  "IsPromotional": false
}
###
POST https://localhost:5001/api/store-products
Content-Type: application/json

{
  "Upc": "123456789022",
  "UpcProm": "123456789012",
  "ProductId": "0ce7436c-aa16-4eea-8b23-01fdf1744f2e",
  "Price": 5.99,
  "Quantity": 100,
  "IsPromotional": true
}
###
PUT https://localhost:5001/api/store-products/123456789012
Content-Type: application/json

{
  "Upc": "123456789014",
  "UpcProm": null,
  "ProductId": "0ce7436c-aa16-4eea-8b23-01fdf1744f2e",
  "Price": 12.99,
  "Quantity": 120,
  "IsPromotional": false
}